wecode-bootcamp-korea/justcode-5-1st-staypler-back

- controllers/room.js
- models/room.js
- routes/room.js
- services/room.js
<br />
- 숙소 리스트 출력 API 구현
<br />
1. 로그인 상태인 경우 id에 user_id 값이 전달되고, 비로그인 경우에는 id에 null이 담긴다고 가정 하에 구현.
2. 로그인 경우 내가 좋아요를 누른 숙소는 좋아요 표시가 활성화 되도록 response값에 isLike(좋아요 여부 컬럼)을 넣어서 전달해준다.
3. 필터링과 정렬 구현은 필터는 동적으로 추가되거나 제가되기 때문에 해당 HAVING, ORDER BY , JOIN문을 함수에서 리턴되도록 구현하여 동적으로 쿼리가 바뀔 수 있게 구현.
4. HTTP 응답 상태 코드를 리소스가 성공적으로 만들어졌다는 201코드에서 요청에 대해 성공했다는 의미의 200코드로 변경
5. async/await 비동기 작업에 대한 에러처리 구문 작성(controllers/rooms.js)
<br />
- prisma.$queryRaw에서는 템플릿 리터럴 문법을 사용하면 문법 에러가 발생하기 때문에 prisma.$qureyRawUnsafe를 사용해야 한다.
- 삼항 연산자 사용과 쿼리문을 동적으로 사용하기 위해 함수로 분해하여 동적으로 사용하는 방법을 알게 되었다...
- 상태코드도 해당 요청에 대한 응답이 어떠냐에 따라 상태코드를 맞게 보내줘야 한다는 것을 알게되었다!
<br />
- 프론트와 연결해보고 문제가 발생하면 추가 수정하겠습니다!
> Add: 숙소 리스트 API 구현 완료

- controllers/user.js
- middleware/authorization.js
- models/user.js
- routes/mypage.js
- routes/room.js
- routes/user.js
- services/user.js
<br />
- 인증 미들웨어를 구현하여 로그인 상태인 회원만이 할 수 있는 기능을 시도할 때 에러 발생 할 수 있게 구현.
<br />
1. 인증 미들웨어를 구현.
2. 인증이 필요한 요청에 인증 미들웨어를 추가
3. me함수를 추가하여 요청 시 토큰을 응답값으로 보낸다.(me함수는 인증 미들웨어를 거치고 실행된다.)
<br />
- 라우터에서 미들웨어를 추가하고 실제 동작하는 것을 확인하니 동작 원리가 조금이나마 이해가 됐습니다.
<br />
> Fix: 인증 미들웨어 수정

- controllers/room.js
- models/room.js
- routes/room.js
- services/room.js
<br />
- 결제 페이지에서 정보를 입력하고 결제 버튼을 클릭하면 예약이 완료되도록 구현.
<br />
1.  같은 날짜에 같은 방을 다른 유저가 먼저 예약할 수 있기 때문에, 예약 체크 함수를 만들어서 예약이 이미 완료된 날짜라면 예약이 실패되고 마감 되었다는 메시지 출력.
2. 예약이 완료된다면 성공 메시지 출력.
<br />
<br />
> Add: 방 예약 기능 구현

- models/room.js
- services/room.js
<br />
- 쿼리문의 WHERE문 조건이 반대로 되어있어서 예약 불가능한 날짜에 예약이 되는 현상 해결
<br />
1. WHERE문 NOT BETWEEN구문에서 NOT을 제거 해주었습니다.
<br />
<br />
> Fix: 방 예약 쿼리 수정

- controllers/user.js
- models/user.js
- services/user.js
<br />
- 마이 페이지에서 비밀번호 변경 기능 구현.
<br />
1. 비밀번호 변경 처리
- 조건문을 통해 현재 비밀번호 일치 체크, 변경할 비밀번호와 확인 비밀번호가 일치하는지 체크
- 조건문을 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현
<br />
<br />
> Add: 비밀번호 변경 기능 구현

- controllers/mypage.js
- controllers/user.js
- routes/mypage.js
- services/mypage.js
- services/user.js
<br />
- 비밀번호 변경 파일 경로 수정 및 검증 코드 수정
<br />
1.  (변경할 비밀번호 && 변경할 비밀번호 확인)  조건을 (변경할 비밀번호 === 변경할 비밀번호 확인)로 수정
<br />
<br />
> Fix: 비밀번호 변경 파일 폴더 이동 및 검증 코드 수정

- controllers/room.js
- models/room.js
- services/room.js
<br />
- 로그인 한 유저가 좋아요 버튼을 누르면 좋아요 테이블에 추가되고 화면 상에 좋아요를 누른 숙소인지 식별 가능하게 구현.
<br />
1. 처음 좋아요를 누르는 숙소는 INSERT가 되도록 하고, 누른 적이 있던 숙소는 UPDATE되도록 구현했습니다.
2. 1번을 구현하기 위해 좋아요 테이블에 해당 데이터가 있는지 찾는 메서드를 작성했습니다.
<br />
<br />
> Add: 좋아요 기능 구현

- controllers/mypage.js
- models/mypage.js
- routes/mypage.js
- services/mypage.js
<br />
- Mypage 관심스테이 리스트 구현
<br />
- 페이지 번호, 페이지당 객체 수, 객체 전체사진 포함 여부(쿼리로 전달)에 따른 리스트 구현
<br />
<br />
> Add: Mypage 관심스테이 리스트 구현

- models/room.js
<br />
- 이미지가 배열 안에 객체 형태로 전달되었는데, url만 배열 안에 넣는 방식으로 수정 
<br />
<br />
<br />
> Fix: 숙소 상세페이지 이미지 전달 방법 수정

- controllers/mypage.js
- controllers/room.js
- controllers/user.js
- models/mypage.js
- models/room.js
- models/user.js
- routes/mypage.js
- routes/room.js
- services/mypage.js
- services/room.js
<br />
- 마이페이지 내 예약 리스트, 관심 리스트 기능
<br />
1. 마이페이지 내 예약 리스트 구현 및 관심 리스트 기능 수정
<br />
<br />
> Fix: 마이페이지 내 예약 리스트, 관심 리스트 기능

- controllers/room.js
- models/main.js
- models/room.js
- services/room.js
- services/user.js
<br />
- 숙소 상세 페이지와 리스트 페이지에서 로그인 한 회원과 아닌 회원을 구분해주기 위해, 컨트롤러에서 header값 체크.
<br />
<br />
<br />
> Fix: 숙소 상세 페이지, 숙소 리스트 기능 controller 수정

- package-lock.json
- package.json
- prisma/schema.prisma
- services/room.js
<br />
- 방이 모두 예약 됐을 시 빈 배열 출력하도록 수정
<br />
-방이 모두 예약 됐을 시 빈 배열 출력하도록 수정
<br />
<br />
> Fix: 방이 모두 예약 됐을 시 빈 배열 출력하도록 수정

- services/user.js
<br />
- 중복 회원 에러메시지 수정
<br />
- 중복 회원 에러메시지 수정
<br />
<br />
> Fix: 중복 회원 에러메시지 수정

- controllers/main.js
- controllers/mypage.js
- controllers/room.js
- controllers/user.js
- middleware/validator.js
- models/mypage.js
- models/room.js
- models/user.js
- routes/main.js
- routes/mypage.js
- routes/room.js
- routes/user.js
- server.js
- services/mypage.js
- services/room.js
- services/user.js
<br />
- 변수, 함수명 재정의 및 회원가입 검증함수 모듈화
- 회원가입 실패 및 성공 시 응답 메시지 수정
<br />
변수, 함수명 재정의 및 회원가입 검증함수 모듈화
<br />
- 변수명고 함수명이 모호하고, 컨벤션도 camel, snake를 섞어서 썼었는데 사용하면서도 헷갈렸습니다.
- 변경하고 나니 확실히 가독성이 좋아졌고, 코드 작성자가 아닌 다른 사람이 봐도 코드를 이해할 수 있을 것 같습니다..
<br />
> Refactor: 변수, 함수명 재정의 및 회원가입 검증함수 모듈화, 회원가입 실패 및 성공 시 응답 메시지 수정

- server.js
<br />
Cors옵션 모든 아이피 허용으로 수정
<br />
> Fix: Cors옵션 모든 아이피 허용으로 수정

- controllers/room.js
- models/mypage.js
- services/mypage.js
<br />
- 토큰 처리 수정
<br />
1. 토큰 처리 수정- 토큰이 없을 때 Bearer null로 값이 넘어오는 것을 확인하고 코드 수정
<br />
<br />
> Fix: 토큰 처리 수정

- models/room.js
- services/room.js
<br />
- 방 이미지 출력을 위해 쿼리 수정
<br />
1. 방 이미지 출력을 위해 쿼리 수정
<br />
<br />
> Fix: 방 이미지 출력을 위해 쿼리 수정

- middleware/authorization.js
- models/room.js
- services/mypage.js
- services/room.js
<br />
- 지역 필터링 조건 추가
- 회원 정보 수정 시 이메일 validation 추가
- 변경된 함수명 수정
<br />
1.지역 필터링 조건 추가
<br />
<br />
> Fix: 지역 필터링 조건 추가

- controllers/mypage.js
- models/mypage.js
- models/room.js
<br />
- 상세페이지 쿼리 템플릿 리터럴 수정
<br />
<br />
<br />
> Fix: 상세페이지 쿼리 템플릿 리터럴 수정

- models/mypage.js
<br />
- 회원 정보 수정 함수명 변경
<br />
1. 회원 정보 수정 함수명 변경
<br />
<br />
> Fix: 회원 정보 수정 함수명 변경

- controllers/room.js
<br />
-응답 메시지에 시작,종료 날짜 추가
<br />
<br />
<br />
> Fix: 응답 메시지에 시작,종료 날짜 추가

- models/room.js
<br />
- 정렬 쿼리 수정
<br />
1. 정렬 쿼리 수정
<br />
<br />
> Fix: 정렬 쿼리 수정
